library('DMwR')
dataset=read.csv("kdd_cup_test.csv")
dataset=dataset[1:100,]
outlier.scores<-lofactor(dataset,5)
jpeg("plot_densities.jpg");
plot(density(log(outlier.scores)))
outliers<-order(outlier.scores,decreasing=T)[1:5]
print(outliers)
n<-nrow(dataset)
labels<-1:n
labels[-outliers]<-"."
jpeg("biplot.jpg");
biplot(prcomp(dataset),cex=2.1,xlabs=labels)
pch<-rep(".",n)
pch[outliers]<-"+"
col<-rep("black",n)
col[outliers]<-"red"
png("scatter_matrix_1.jpg");
pairs(dataset[,1:7],pch=pch,col=col)
png("scatter_matrix_2.jpg");
pairs(dataset[,8:14],pch=pch,col=col)
png("scatter_matrix_3.jpg");
pairs(dataset[,15:21],pch=pch,col=col)
png("scatter_matrix_4.jpg");
pairs(dataset[,22:28],pch=pch,col=col)
png("scatter_matrix_5.jpg");
pairs(dataset[,22:28],pch=pch,col=col)
png("scatter_matrix_6.jpg");
pairs(dataset[,29:35],pch=pch,col=col)
png("scatter_matrix_7.jpg");
pairs(dataset[,36:41],pch=pch,col=col)
png("scatter_matrix.jpg");
pairs(dataset,pch=pch,col=col)
dev.off()